version: 2.1

jobs:
  build:
    docker:
      - image: docker:latest

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker image
          command: |
            echo "FROM nginx:2.1" >> Dockerfile
            echo "COPY . /usr/share/nginx/html/" >> Dockerfile
            docker build -t your-image-name .

workflows:
  version: 2
  build-only:
    jobs:
      - build
