version: 2.1

jobs:
  build:
    docker:
      - image: docker:latest

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker image
          command: |
            echo "FROM httpd:2.4" >> Dockerfile
            echo "EXPOSE 8001" >> Dockerfile
            echo "COPY . . /usr/local/apache2/htdocs/" >> Dockerfile
            docker build -t my_portfilo .


workflows:
  version: 2
  build-only:
    jobs:
      - build
