version: 2.1

jobs:
  build:
    docker:
      - image: docker:latest

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker image
          command: |
            docker build -t my_portfilo .
      - run:
          name: Push Docker image to registry
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag my_portfilo "$DOCKERHUB_USERNAME/my_portfilo:latest"
            docker push "$DOCKERHUB_USERNAME/my_portfilo:latest"        

workflows:
  version: 2
  build-only:
    jobs:
      - build
