version: 2.1

jobs:
  build:
    docker:
      - image: circleci/docker:latest

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker image
          command: |
            echo "FROM httpd:2.4" >> Dockerfile
            echo "EXPOSE 8001" >> Dockerfile
            echo "COPY . /usr/local/apache2/htdocs/" >> Dockerfile
            docker build -t project_altaf .

      - run:
          name: Push Docker image to registry
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag project_altaf "$DOCKERHUB_USERNAME/project_altaf:latest"
            docker push "$DOCKERHUB_USERNAME/project_altaf:latest"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
