version: 2.1

jobs:
  build:
    docker:
      - image: docker:latest

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker image
          command: |
            docker build -t my_portfilo .
      - run:
          name: Push Docker image to registry
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag my_portfilo "$DOCKERHUB_USERNAME/my_portfilo:latest"
            docker push "$DOCKERHUB_USERNAME/my_portfilo:latest"        

  deploy:
    docker:
      - image: docker:latest

    steps:
      - attach_workspace:
          at: .

      - setup_remote_docker

      - add_ssh_keys:
         fingerprints:
           - "MD5:77:e7:1a:ba:85:eb:da:37:ff:2e:d5:29:04:c8:32:0a"

      - run:
          name: Deploy to NGINX server
          command: |
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh "$USER_NAME"@"$IP" 'sudo apt update'


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

